runtime: nodejs20

env: standard

instance_class: F2

env_variables:
  PORT: "8080"

handlers:
  - url: ".*"
    script: auto
    secure: always

automatic_scaling:
  max_instances: 1
  max_idle_instances: 0
