runtime: nodejs20

env: standard

instance_class: F2

env_variables:
  PORT: 8080

automatic_scaling:
  max_instances: 1
  max_idle_instances: 0

handlers:
  - url: /.*
    secure: always
    script: auto
  - url: /(.*\.(gif|png|jpg))$
    static_files: /build/client/\1
    upload: /build/client/.*\.(gif|png|jpg)$
    secure: always
  - url: /favicon.ico
    static_dir: /build/client/favicon.ico
    secure: always
